services:
  - type: web
    name: monad-faucet
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    rootDir: backend
    healthCheckPath: /api/info
    envVars:
      - key: PORT
        value: 8080
      - key: ARB_RPC_URL
        sync: true
      - key: MONAD_RPC_URL
        sync: true
      - key: WALLET_PRIVATE_KEY
        sync: true
      - key: ADMIN_API_KEY_1
        sync: true
      - key: ADMIN_API_KEY_2
        sync: true
