services:
  - type: web
    name: monad-faucet
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/info
    envVars:
      - key: PORT
        value: 8080
      # Add other environment variables as needed
      # - key: ETH_NODE_URL
      #   sync: false # This means you'll set it manually in the Render dashboard
      # - key: MONAD_NODE_URL
      #   sync: false 